# X API (OAuth 1.0a)
X_API_KEY = "m6J9eF6IxcYt7n3wnMkOEDuNU"
X_API_KEY_SECRET = "cmP0OBt2HVwYhFyAwxIloi8e4acHdI0dns5KYRAyVmsyNAD0cg"
X_ACCESS_TOKEN = "1940203372625477632-baqyYgjn96Vlr1TSeDtsq74o5Vxv7a"
X_ACCESS_TOKEN_SECRET = "9rXyuAwBSgsRUqQav8d7AVj25T1xGzdpP4ZUWNqAUiKtt"

# Anthropic
ANTHROPIC_API_KEY = "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"
